name: Build

on:
  push:
    branches: [production, testing]
  pull_request:
    branches: [production, testing]

jobs:
  build:
    runs-on: ubuntu-latest

strategy:
  matrix:
    node-version: [15.x]

steps:
  - uses: actions/checkout@v2
  - name: Node.js
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version}}
  - run: npm i -g yarn
  - name: yarn install, build and test
    run: |
      yarn install
      yarn run test
