name: Build

on:
  push:
    branches: [production, testing]
  pull_request:
    branches: [production, testing]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - name: yarn setup
        run: yarn install && yarn run test && yarn run build && yarn run clean
